CREATE TABLE USUARIO
(
ID_USUARIO INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
NOMBRE VARCHAR(40) NOT NULL,
APELLIDOS VARCHAR(60),
EMAIL VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(50) NOT NULL,
ACTIVO BOOLEAN NOT NULL,
ADMINISTRADOR BOOLEAN NOT NULL
);
CREATE TABLE HORARIO
(
ID_HORARIO INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
FECHA DATE NOT NULL,
HORA_ENTRADA TIME NOT NULL,
HORA_SALIDA TIME,
ID_USUARIO INTEGER NOT NULL,
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
);
INSERT INTO USUARIO (NOMBRE,APELLIDOS,EMAIL,PASSWORD,ACTIVO,ADMINISTRADOR)
VALUES('Adrian','Ruiz','a@ruiz.es','a',true,true);
INSERT INTO USUARIO (NOMBRE,APELLIDOS,EMAIL,PASSWORD,ACTIVO,ADMINISTRADOR)
VALUES('Tyson','Ruiz','t@ruiz.es','a',true,false);

